import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { connectDB } from "./services/mongo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home - Book Store",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const conn = await connectDB();
  console.log(conn);
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
